import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Jumbotron from '../components/Jumbotron'
import Project from '../components/Project'
import Skill from '../components/Skill'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hilal Akbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Jumbotron />
      <About />
      <Skill />
      <Project />
      <Contact />
    </div>
  )
}
